version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3060:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend/
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/schemax
      - PORT=80
    # depends_on:
    #   - db

#   db:
#     image: postgres:15-alpine
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=schemax
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

networks:
  internal:
    driver: bridge