services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - ./apps/api/.env
    environment:
      - PORT=80
      - BETTER_AUTH_URL=http://localhost:3060
    networks:
      - internal

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        INTERNAL_BACKEND_URL: http://api
        NEXT_PUBLIC_BACKEND_URL: http://localhost:3060/api
    ports:
      - "3060:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=/api
      - INTERNAL_BACKEND_URL=http://api
    depends_on:
      - api
    networks:
      - internal

networks:
  internal:
    driver: bridge
